/*
This query should find all PK to 6 classes that have a schedule attached to them.

For how _we_ handle attendnace at our schools, having a schedule attached to these classes
caused issues, so we needed to identify them and un-schedule them.
*/

SELECT 
	MSS_SCHOOL.SKL_SCHOOL_NAME,
	MSS_SCHEDULE_MASTER.MST_SECTION_NUMBER,
	MSS_SCHEDULE_MASTER.MST_SCHEDULE_DISPLAY,
	MSS_SCHEDULE_MASTER.MST_STAFF_VIEW,
	MSS_SCHEDULE_MASTER.MST_COURSE_VIEW,
	MSS_SCHEDULE_MASTER.MST_DESCRIPTION,
	MSS_SCHEDULE_MASTER.MST_TERM_VIEW,
	MSS_COURSE_SCHOOL.CSK_GRADE_LEVEL

  FROM 
	MSS_SCHEDULE_MASTER
	LEFT JOIN MSS_COURSE_SCHOOL ON MSS_SCHEDULE_MASTER.MST_CSK_OID=MSS_COURSE_SCHOOL.CSK_OID
	LEFT JOIN MSS_SCHOOL ON MSS_COURSE_SCHOOL.CSK_SKL_OID=MSS_SCHOOL.SKL_OID

  WHERE
    MSS_SCHEDULE_MASTER.MST_SCHEDULE_DISPLAY IS NOT NULL
	AND MSS_COURSE_SCHOOL.CSK_GRADE_LEVEL NOT IN ('00', '07', '08', '09', '10', '11', '12')

  ORDER BY 
	SKL_SCHOOL_NAME ASC,
	MSS_SCHEDULE_MASTER.MST_DESCRIPTION ASC

