SELECT DISTINCT
	SKL.SKL_SCHOOL_NAME AS 'School',
	CSK.CSK_SHORT_DESCRIPTION AS 'Course',
	GTD.GTD_DESCRIPTION AS 'Transcript Definition',
	RBD.RBD_NAME AS 'Rubric Definition'
FROM MSS_COURSE_SCHOOL CSK
INNER JOIN MSS_SCHOOL SKL ON CSK.CSK_SKL_OID = SKL.SKL_OID
LEFT OUTER JOIN MSS_GRADE_TRANSCRIPT_DEFINITION GTD ON CSK.CSK_GTD_OID = GTD.GTD_OID
INNER JOIN MSS_COURSE_SCHEDULE CSS ON CSK.CSK_OID = CSS.CSS_CSK_OID
INNER JOIN MSS_SCHEDULE SCH ON CSS.CSS_SCH_OID = SCH.SCH_OID
LEFT OUTER JOIN MSS_RUBRIC_DEFINITION RBD ON CSK.CSK_RBD_OID = RBD.RBD_OID
WHERE SCH.SCH_START_DATE = '2022-08-01 00:00:00.000'
ORDER BY SKL.SKL_SCHOOL_NAME