SELECT DISTINCT 
	SKL.SKL_SCHOOL_NAME, 
	CSK.CSK_COURSE_DESCRIPTION, 
	CSK.CSK_COURSE_NUMBER, 
	RBD.RBD_DESCRIPTION 
FROM 
	MSS_COURSE_SCHOOL CSK
INNER JOIN 
	MSS_SCHOOL SKL ON CSK.CSK_SKL_OID = SKL.SKL_OID
INNER JOIN 
	MSS_RUBRIC_DEFINITION RBD ON CSK.CSK_RBD_OID = RBD.RBD_OID
WHERE 
	SUBSTRING(CSK_COURSE_DESCRIPTION,1,1) != SUBSTRING(RBD_DESCRIPTION,1,1)  