SELECT
    SKL.SKL_SCHOOL_NAME AS School,
    SUM(CASE WHEN STD.STD_GRADE_LEVEL = '01' THEN 1 ELSE 0 END) AS 'Grade 1 Enrollment',
    SUM(CASE WHEN STD.STD_GRADE_LEVEL = '02' THEN 1 ELSE 0 END) AS 'Grade 2 Enrollment',
    SUM(CASE WHEN STD.STD_GRADE_LEVEL = '03' THEN 1 ELSE 0 END) AS 'Grade 3 Enrollment',
    SUM(CASE WHEN STD.STD_GRADE_LEVEL IN ('01', '02', '03') THEN 1 ELSE 0 END) AS 'Total'
FROM 
    MSS_SCHOOL SKL
INNER JOIN
    MSS_STUDENT STD ON SKL.SKL_OID = STD.STD_SKL_OID
WHERE
    STD_ENROLLMENT_STATUS LIKE 'Active%'
GROUP BY
    SKL.SKL_SCHOOL_NAME
HAVING
    SUM(CASE WHEN STD.STD_GRADE_LEVEL IN ('01', '02', '03') THEN 1 ELSE 0 END) > 0
ORDER BY
    SKL.SKL_SCHOOL_NAME
