SELECT 
	SC.SKL_SCHOOL_NAME AS School,
	PR.PSN_NAME_FIRST AS LegalFirstName,
	PR.PSN_NAME_LAST AS LegalLastName,
	ST.STD_ID_STATE AS LearningID,
	PR.PSN_DOB AS DateOfBirth,
	PR.PSN_GENDER_CODE AS Gender,
	ST.STD_GRADE_LEVEL AS Grade,
	ST.STD_HOMEROOM AS Homeroom,
	ST.STD_HR_TEACHER_VIEW AS HomeroomTeacher,
	PR.PSN_FIELDB_002 AS IndigenousDeclaration,
	EN.ENR_ENROLLMENT_DATE AS EnrollmentDate
FROM 
	MSS_STUDENT ST
INNER JOIN 
	MSS_STUDENT_ENROLLMENT EN ON ST.STD_OID = EN.ENR_STD_OID AND EN.ENR_ENROLLMENT_TYPE = 'E'
INNER JOIN
	MSS_SCHOOL SC ON EN.ENR_SKL_OID = SC.SKL_OID
INNER JOIN
	MSS_PERSON_STD PR ON ST.STD_PSN_OID = PR.PSN_OID
WHERE 
	EN.ENR_ENROLLMENT_DATE >= '2021-09-15' AND EN.ENR_ENROLLMENT_DATE <= '2021-11-15' 
	AND ST.STD_GRADE_LEVEL NOT IN ('0K','PK') AND ST.STD_GRADE_LEVEL IN ('01','02','03','04','05','06')
ORDER BY
	School,
	LegalLastName,
	LegalFirstName