DECLARE 
	@STARTDATE AS DATETIME,
	@ENDDATE AS DATETIME
SET 
	@STARTDATE = '2021-09-15'
SET
	@ENDDATE = '2021-11-15'

SELECT
	SC.SKL_SCHOOL_NAME AS School,
	PR.PSN_NAME_FIRST AS LegalFirstName,
	PR.PSN_NAME_LAST AS LegalLastName,
	ST.STD_ID_STATE AS LearningID,
	PR.PSN_DOB AS DateOfBirth,
	PR.PSN_GENDER_CODE AS Gender,
	ST.STD_GRADE_LEVEL AS Grade,
	ST.STD_HOMEROOM AS Homeroom,
	ST.STD_HR_TEACHER_VIEW AS HomeroomTeacher,
	PR.PSN_FIELDB_002 AS IndigenousDeclaration,
	E.ENR_ENROLLMENT_DATE,
	ST.STD_ENROLLMENT_STATUS
FROM 
	MSS_STUDENT ST
INNER JOIN
	MSS_SCHOOL SC ON ST.STD_SKL_OID = SC.SKL_OID
INNER JOIN
	MSS_PERSON_STD PR ON ST.STD_PSN_OID = PR.PSN_OID
INNER JOIN
(SELECT 
	TOP 1 WITH TIES
	ENR_STD_OID,
	ENR_ENROLLMENT_DATE,
	ENR_ENROLLMENT_TYPE,
	ENR_TIMESTAMP
FROM	
	MSS_STUDENT_ENROLLMENT
WHERE 
	ENR_ENROLLMENT_TYPE = 'E'
ORDER BY 
	ROW_NUMBER() OVER (PARTITION BY ENR_STD_OID ORDER BY ENR_ENROLLMENT_DATE DESC)
) E
ON ST.STD_OID = E.ENR_STD_OID
LEFT JOIN
(SELECT 
	TOP 1 WITH TIES
	ENR_STD_OID,
	ENR_ENROLLMENT_DATE,
	ENR_ENROLLMENT_TYPE,
	ENR_TIMESTAMP
FROM	
	MSS_STUDENT_ENROLLMENT
WHERE 
	ENR_ENROLLMENT_TYPE = 'W'
ORDER BY 
	ROW_NUMBER() OVER (PARTITION BY ENR_STD_OID ORDER BY ENR_ENROLLMENT_DATE DESC)
) W
ON ST.STD_OID = W.ENR_STD_OID
WHERE 
	(W.ENR_TIMESTAMP IS NULL OR E.ENR_TIMESTAMP > W.ENR_TIMESTAMP)
	AND
	ST.STD_GRADE_LEVEL IN ('0K','PK')

UNION ALL

SELECT 	
	SC.SKL_SCHOOL_NAME AS School,
	PR.PSN_NAME_FIRST AS LegalFirstName,
	PR.PSN_NAME_LAST AS LegalLastName,
	ST.STD_ID_STATE AS LearningID,
	PR.PSN_DOB AS DateOfBirth,
	PR.PSN_GENDER_CODE AS Gender,
	ST.STD_GRADE_LEVEL AS Grade,
	ST.STD_HOMEROOM AS Homeroom,
	ST.STD_HR_TEACHER_VIEW AS HomeroomTeacher,
	PR.PSN_FIELDB_002 AS IndigenousDeclaration,
	EN.ENR_ENROLLMENT_DATE,
	ST.STD_ENROLLMENT_STATUS
FROM 
	MSS_STUDENT ST
INNER JOIN 
	MSS_STUDENT_ENROLLMENT EN ON ST.STD_OID = EN.ENR_STD_OID AND EN.ENR_ENROLLMENT_TYPE = 'E'
INNER JOIN
	MSS_SCHOOL SC ON EN.ENR_SKL_OID = SC.SKL_OID
INNER JOIN
	MSS_PERSON_STD PR ON ST.STD_PSN_OID = PR.PSN_OID
WHERE 
	EN.ENR_ENROLLMENT_DATE >= @STARTDATE AND EN.ENR_ENROLLMENT_DATE <= @ENDDATE 
	AND ST.STD_GRADE_LEVEL IN ('0K','PK') 
ORDER BY
	School, 
	Grade,
	LegalLastName,
	LegalFirstName
