SELECT  
	SKL.SKL_SCHOOL_NAME AS School,
	STF.STF_NAME_VIEW AS Teacher,
	STAS.ASM_GRADE_LEVEL_CODE AS Grade,
	STD.STD_ID_STATE AS 'Learning ID',
	STD.STD_NAME_VIEW AS Student,
	FORMAT(STAS.ASM_DATE, 'MM-dd-yyyy') AS Date,
	STAS.ASM_FIELDA_001 AS Level
FROM MSS_STUDENT_ASSESSMENT STAS
INNER JOIN MSS_STUDENT STD ON STAS.ASM_STD_OID = STD.STD_OID
INNER JOIN MSS_SCHOOL SKL ON STAS.ASM_SKL_OID = SKL.SKL_OID
INNER JOIN MSS_STAFF STF ON STD.STD_HOMEROOM = STF.STF_HOMEROOM 
ORDER BY
	SKL.SKL_SCHOOL_NAME,
	STAS.ASM_GRADE_LEVEL_CODE,
	STF.STF_NAME_VIEW,
	STD.STD_NAME_VIEW