SELECT 
	ST.STD_NAME_VIEW,
	FORMAT(E.ENR_ENROLLMENT_DATE,'MM/dd/yyyy')
FROM 
	MSS_STUDENT ST
INNER JOIN
	(SELECT 
	TOP 1 WITH TIES
		ENR_STD_OID,
		ENR_ENROLLMENT_DATE,
		ENR_ENROLLMENT_TYPE,
		ENR_TIMESTAMP
	FROM	
		MSS_STUDENT_ENROLLMENT
	WHERE 
		ENR_ENROLLMENT_TYPE = 'E'
	ORDER BY 
		ROW_NUMBER() OVER (PARTITION BY ENR_STD_OID ORDER BY ENR_ENROLLMENT_DATE DESC)
	) E
ON 
	ST.STD_OID = E.ENR_STD_OID
WHERE
	STD_ID_LOCAL in (
	'PUPILNUMBERGOESHERE',
	'PUPILNUMBERGOESHERE'
	)
ORDER BY
	ST.STD_NAME_VIEW