SELECT T1.*, T2.[ENROLLED THIS YEAR], T3.[WITHDRAWN THIS YEAR], T4.[RETURNED] FROM
/* CURRENT STUDENTS */
(SELECT 
	SKL.SKL_SCHOOL_NAME AS 'SCHOOL',
	COUNT(STD.STD_SKL_OID) AS 'CURRENTLY ENROLLED'
FROM 
	MSS_STUDENT STD
INNER JOIN
	MSS_SCHOOL SKL ON STD.STD_SKL_OID = SKL.SKL_OID
WHERE
	STD.STD_ENROLLMENT_STATUS NOT IN ('Comp Sch','Withdrawn')
GROUP BY
	SKL.SKL_SCHOOL_NAME,
	STD.STD_SKL_OID) T1
JOIN
/* ENROLLED STUDENTS AS OF THIS YEAR */
(SELECT 
	SKL.SKL_SCHOOL_NAME,
	COUNT (ENR.ENR_SKL_OID) AS 'ENROLLED THIS YEAR'
FROM
	MSS_STUDENT STD
INNER JOIN
	MSS_STUDENT_ENROLLMENT ENR ON STD.STD_OID = ENR.ENR_STD_OID
INNER JOIN
	MSS_SCHOOL SKL ON ENR.ENR_SKL_OID = SKL.SKL_OID
WHERE
	ENR.ENR_ENROLLMENT_TYPE = 'E' AND ENR.ENR_ENROLLMENT_DATE > '2022-07-31'
GROUP BY 
	SKL.SKL_SCHOOL_NAME,
	ENR.ENR_SKL_OID) T2
ON
	T1.[SCHOOL] = T2.SKL_SCHOOL_NAME
JOIN
/* WITHDRAWN STUDENTS */
(SELECT 
	SKL.SKL_SCHOOL_NAME,
	COUNT (ENR.ENR_SKL_OID) AS 'WITHDRAWN THIS YEAR'
FROM
	MSS_STUDENT STD
INNER JOIN
	MSS_STUDENT_ENROLLMENT ENR ON STD.STD_OID = ENR.ENR_STD_OID
INNER JOIN
	MSS_SCHOOL SKL ON ENR.ENR_SKL_OID = SKL.SKL_OID
WHERE
	ENR.ENR_ENROLLMENT_TYPE = 'W' AND ENR.ENR_ENROLLMENT_DATE > '2022-07-31'
GROUP BY 
	SKL.SKL_SCHOOL_NAME,
	ENR.ENR_SKL_OID) T3
ON
	T1.[SCHOOL] = T3.SKL_SCHOOL_NAME
JOIN
/* NUMBER OF WITHDRAWN STUDENTS WHO ARE CURRENT AGAIN */
(SELECT 
	SKL.SKL_SCHOOL_NAME,
	COUNT (ENR.ENR_SKL_OID) AS 'RETURNED'
FROM
	MSS_STUDENT STD
INNER JOIN
	MSS_STUDENT_ENROLLMENT ENR ON STD.STD_OID = ENR.ENR_STD_OID
INNER JOIN
	MSS_SCHOOL SKL ON ENR.ENR_SKL_OID = SKL.SKL_OID
WHERE
	ENR.ENR_ENROLLMENT_TYPE = 'W' AND ENR.ENR_ENROLLMENT_DATE > '2022-07-31' AND STD.STD_ENROLLMENT_STATUS NOT IN ('Comp Sch','Withdrawn') AND STD.STD_SKL_OID = ENR.ENR_SKL_OID
GROUP BY 
	SKL.SKL_SCHOOL_NAME,
	ENR.ENR_SKL_OID) T4
ON T1.[SCHOOL] = T4.SKL_SCHOOL_NAME
ORDER BY T1.[SCHOOL]


SELECT 
	SKL.SKL_SCHOOL_NAME,
	COUNT(STD.STD_OID)
FROM
	MSS_STUDENT STD
INNER JOIN
	MSS_STUDENT_ENROLLMENT ENRW ON ENRW.ENR_OID IN (SELECT ENR_OID FROM MSS_STUDENT_ENROLLMENT WHERE ENR_STD_OID = STD.STD_OID AND ENR_ENROLLMENT_TYPE = 'W' AND ENR_ENROLLMENT_DATE > '2022-09-01' )
INNER JOIN
	MSS_SCHOOL SKL ON ENRW.ENR_SKL_OID = SKL.SKL_OID 
INNER JOIN
	MSS_STUDENT_ENROLLMENT ENRE ON ENRE.ENR_OID IN (SELECT ENR_OID FROM MSS_STUDENT_ENROLLMENT WHERE ENR_STD_OID = STD.STD_OID AND ENR_SKL_OID = ENRW.ENR_SKL_OID AND ENR_ENROLLMENT_TYPE = 'E' AND ENR_ENROLLMENT_DATE > ENRW.ENR_ENROLLMENT_DATE) 
WHERE
	ENRE.ENR_SKL_OID = ENRW.ENR_SKL_OID
GROUP BY 
	SKL.SKL_SCHOOL_NAME
ORDER BY
	SKL.SKL_SCHOOL_NAME
